name: Run SQL from Multiple Repos

on:
  workflow_dispatch:
    inputs:
      repo_names:
        description: 'Comma-separated repo names (e.g. sqlrepo1,sqlrepo2)'
        required: true
      branch_name:
        description: 'Branch to pull from (e.g. main)'
        required: true

jobs:
  run-sql:
    runs-on: self-hosted
    env:
      SQL_SERVER: ${{ secrets.SQL_SERVER }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASS: ${{ secrets.SQL_PASS }}
      CENTRAL_PAT: ${{ secrets.CENTRAL_PAT }}

    steps:
      - name: Parse repo names and execute SQLs
        shell: powershell
        run: |
          $repos = "${{ github.event.inputs.repo_names }}".Split(',')
          $branch = "${{ github.event.inputs.branch_name }}"

          foreach ($repo in $repos) {
            $repo = $repo.Trim()
            Write-Host "Cloning $repo on branch $branch"

            git clone --branch $branch https://x-access-token:${env:CENTRAL_PAT}@github.com/pnamilak/$repo.git temp-$repo
            Set-Location temp-$repo

            Write-Host "Finding changed SQL files in $repo"
            $changedFiles = git log -1 --name-only --pretty=""
            $sqlFiles = $changedFiles | Where-Object { $_ -like "*.sql" }

            if ($sqlFiles.Count -eq 0) {
              Write-Host "No .sql files found in last commit of $repo"
            } else {
              foreach ($file in $sqlFiles) {
                Write-Host "Executing $file..."
                & sqlcmd -S "$env:SQL_SERVER" -U "$env:SQL_USER" -P "$env:SQL_PASS" -i "$file"
              }
            }

            Set-Location ..
            Remove-Item -Recurse -Force "temp-$repo"
          }
